### PR TITLE
bug: get replica name or domain

### LINKED ISSUE #156: bug: getReplica only accepts domain
`getReplica` should accept `nameOrDomain` and `resolveDomainName`

### PR DESCRIPTION
**Pull request by ErinHales**
Closes #156

`getReplica` on NomadContext only accepts domain number where everything else accepts nameOrDomain

## Solution

Pass in nameOrDomain, resolveDomain

## PR Checklist

- [x] Added Tests
- [x] Updated Documentation
- [x] Updated CHANGELOG.md for the appropriate package

### CODE REVIEW

File: packages/sdk/src/CoreContracts.ts [hunk 1]
```diff
@@ -29,7 +29,8 @@ export class CoreContracts<T extends NomadContext> extends Contracts<
     this.conf = conf;
   }
 
-  getReplica(domain: string): core.Replica | undefined {
+  getReplica(nameOrDomain: string | number): core.Replica | undefined {
+    const domain = this.context.resolveDomain(nameOrDomain);
     if (!this.connection) throw new NoProviderError(this.context, domain);
     const replica = this.conf.replicas[domain];
```
Comment (prestwich) [inline packages/sdk/src/CoreContracts.ts:41]: why is this not a type error?

`domain` is a `number`
`this.conf.replicas` is a `Record<string, _>`

why can we index it with a number? this is a bug. Need to use `resolveDomainName` on L33

**Review by prestwich — CHANGES_REQUESTED** [review]

**Review by prestwich — APPROVED** [review]
